# Copyright © 2024 Brent Tunnicliff <brent@tunnicliff.dev>

name: 'Publish app'
description: 'Common app publish action for my android projects.'
runs:
  using: "composite"
  steps:
    - name: Build apk debug
      shell: bash
      run: ./gradlew assembleDebug
    - name: Upload APK Debug
      uses: actions/upload-artifact@v4
      with:
        name: Debug apk
        path: app/build/outputs/apk/debug/
    - name: Build apk release (unsigned)
      shell: bash
      run: ./gradlew assembleRelease
    - name: Upload APK Release
      uses: actions/upload-artifact@v4
      with:
        name: Release APK (unsigned)
        path: app/build/outputs/apk/release/